### ISSUE TITLE
Some function keys stop responding on Mini Pro

### ISSUE THREAD

**Issue by unrealdtc** [vx/connectbot#8]
Device : Xperia Mini Pro (SK17i)
VX connectbot version : 1.7.1-16
Custom Keymap configuration : Sony Ericsson Xperia (mini) pro

Description : sometimes shift key and the blue function key stop responding in VX connectbot (and only in VX connectbot). If I kill and restart VX connectbot, they work again.

**Comment by mmatuska** [comment]
I have experienced the very same (sometimes). I have to investigate, why this happens. A workaround is to slide the hardware keyboard close and open again.

**Comment by c---** [comment]
I get the same issue on my G2.  The ALT, SHIFT, etc stop working.

The issue is easily reproduced:
1. Start connection
2. Close the keyboard
3. Disconnect
4. Open keyboard
5. Start a connection and the keys won't work

I'm starting the connection via a direct home screen widget, not using the VX gui.  Not sure if that makes a difference or not.
